language: python
python:
    - "3.7-dev"  # 3.7 development branch
install:
  - pip3 install pipenv
branches:
  only:
     - master

deploy:
  - provider: codedeploy
    revision_type: github
    access_key_id: "kkD1Kcu3+JnlK/mZ9hqKyqgcfyA0Q6gn+52/TrWIZ7JBB+tHc5wLmFEezzrzs8a8/Yw14QLV8sm4FHoh4gU78t1CwfCIRiOdeltvm1k1hi5LzKM7faVhyYtGOydOqEp7UgNMJqj47naew4VOEpLnaZDpWWYn5QPnWZk8mgMkRpkanTnAhcsNRT31/EF9P8K1iaDPwx/2tb/cfC6Z+QDKk9PxSLuWrm7yjfDDjqnWWmvTaEUJNJV8S0TeEQNs1GjBWobnxy/buAt7YJyylSHjqX+JoImEw4h/gjPEDF7CtrQzG5cWZeXEZ2V+oDvs43i4Vpopgg+mHF15LKvj8g2DuldquhFkQ6vIR+MDwnG5ZLlKnMHA4UceVmv1kff6wvFk0uizd9fFvmBAR5b88ZxvMW79N0gGNG+NilDEyxQ5+OVFbrMJNh1r2ztJOB63a2F1KUUD0uiMLLQHtumJn4nyzEnlQsZ6TFaGaWvtuOt3ahB3F5Q6vPb93okZBrOpeUY7cwVtkbNTq9ea79qoqpddvq+LQCXo2nlEl5hGjv3KCqToFNWyY5Iz7GMf81D9/1hUY6ePYwuTNc6HrwUA3VukkcxJ2aRpvPEe5v6x607IuOJVqQBU64nTFgc16LoRYQ76PTDGiqELR8rkwwFLXW1Vehwv1gDNCLmxR1X6WIS694A="
    secret_access_key: "n3nu1MWgq75jFVp2Q2G+qO121+oHOYEHpLmL/iFHM1LOqL4CvV4mwmc34sw0AmAnnnaL27wfnsZKcoC1KD3m5tdPmZ4lqqS7Hw4cZXZi+3Ge/8k2QtHtyfKp+u8UWotgwse/JIQNq36hUugIhkrRnAHMVKShkYLwjiTvou/CfwfbD/6sLj/v8B8bDbg7sN5Xt/GPhzSvVAE7WTPIw2KFxz/Yi+XHVUhlsD3ahuZoLiFBEIBgGj8Nekjbkg5rph7nYEGKIARdBlhBwKuULxNlSpZ77OnCSEawZxWfdMV8OCzNdoLZEqrC0KrOHY1IgJIgPwKuPRDdn6f9DiT6140vcEG/m15qxo+79K6d2+mjZDe2C+lrjMEV81ENx6Q9xwux+f7XI8aUiy39qu6aGqMls4wbbcu11prWAAiZAob7dd/2L4zGVzGSsSzDtMhGPQS80TqapDfr2QKXHc6HlAH32PA4MBNxYhZaC5d2gPxAsVQuyEYIP8rrqDDyh9NxJDCi0BisDpIcDw+93S8BvL3VSdApVatfregW4jultSF1to+t7zF+ZM28SHJAFEWcEL3O7lm2gxssgDKFFK+4GRWTOWTpkJ2DWTWyi/YDOJsyx/OH8NHh76IIZq0r9+AjYp6f5WSfiClIacgxNo3KCZ1EIeojCVaT8MN78QvXH6ZG3Js="
    application: CodeDeployGitHubDemo-App
    deployment_group: CodeDeployGitHubDemo-DepGrp
    region: us-east-1
    sudo: enabled
    script: ./updateapp.sh
    script: ./scripts/test.sh
    
    
