---
- hosts: pythonapp
  remote_user: ubuntu

  tasks:
    - name: Run apt-get update.
      sudo: yes
      apt: update_cache=yes

    - name: Install dependencies packages.
      sudo: yes
      apt: name={{ item }} state=present
      with_items:
         - tar
         - build-essential
         - checkinstall
         - libreadline-gplv2-dev
         - libncursesw5-dev
         - libssl-dev
         - libsqlite3-dev
         - tk-dev
         - libgdbm-dev
         - libc6-dev
         - libbz2-dev
         - zlib1g-dev
         - openssl
         - libffi-dev
         - python3-dev
         - python3-setuptools
         - wget

    - name: Create python37 directory.
      sudo: no
      file: path=/tmp/Python37 state=directory mode=0755

    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive: src=https://www.python.org/ftp/python/3.7.0/Python-3.7.0.tar.xz dest=/tmp/Python37 remote_src=yes

    - name: run configure python3.7.0
      shell: './configure'
      args:
        chdir: /tmp/Python37/Python-3.7.0

    - name: run make python 3.7.0
      sudo: yes
      shell: 'make altinstall'
      args:
        chdir: /tmp/Python37/Python-3.7.0

    - name: run pip install pipenv
      sudo: yes
      shell: 'pip3.7 install pipenv'

    - name: Clone Application repo
      git: repo=https://github.com/BakishMaayan/Kin.git dest=/home/ubuntu/Kin clone=yes update=no

    - name: run install.sh
      sudo: yes
      shell: 'bash install.sh'
      args:
        chdir: /home/ubuntu/Kin

    - name: run run.sh
      sudo: yes
      shell: 'nohup bash run.sh &'
      args:
        chdir: /home/ubuntu/Kin
